## CE9010: Introduction to Data Analysis
## Semester 2 2018/19
## Xavier Bresson
<hr>

## Tutorial 2: Linear algebra in Python
## Objective
### $\bullet$ Review of linear algebra basics
<hr>

<br>
## 1. Matrix, vector and scalar representation
<hr>
### 1.1 Matrix 
Example:
$$
X = \left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]
$$

$X_{ij}$ is the element at the $i^{th}$ row and $j^{th}$ column. Here: $X_{11}=4.1,X_{32}=-1.8$.

Dimension of matrix $X$ is the number of rows times the number of columns. <br>
Here $dim(X)=3\times 2$. $X$ is said to be a $3\times 2$ matrix. 

The set of all $3\times 2$ matrices is $\mathbb{R}^{3\times 2}$.


### 1.2 Vector 
Example: 
$$
x = \left[ 
\begin{array}{cccc}
4.1 \\ 
-3.9 \\ 
6.4 
\end{array} 
\right]
$$

$x_i=i^{th}$ element of $x$. Here: $x_1=4.1,x_3=6.4$.

Dimension of vector $x$ is the number of rows. <br>
Here $dim(x)=3\times 1$ or $dim(x)=3$. $x$ is said to be a 3-dim vector.

The set of all 3-dim vectors is $\mathbb{R}^3$.

### 1.3 Scalar 
Example: 
$$
x=5.6
$$

A scalar has no dimension.

The set of all scalars is $\mathbb{R}$.

Note: $x=[5.6]$ is a 1-dim vector, not a scalar.

<br>

### Question 1: Represent the previous matrix, vector and scalar in Python
Hint: You may use numpy library, shape(), type(), dtype.

In [13]:
import numpy as np

X = np.array([[4.1,5.3],[-3.9,8.4],[6.4,-1.8]],dtype=float)
print('This is a 3 by 2 matrix.')
print(X)
print(X.shape,type(X),X.dtype)
print('')


X = np.array([[4.1],[-3.9],[6.4]],dtype=float)
print('This is a 3 by 1 vector.')
print(X)
print(X.shape,type(X),X.dtype)
print('')


X = np.asscalar(np.array([5.6]))
print('This is a scalar.')
print(X)
print(type(X))

This is a 3 by 2 matrix.
[[ 4.1  5.3]
 [-3.9  8.4]
 [ 6.4 -1.8]]
(3, 2) <class 'numpy.ndarray'> float64

This is a 3 by 1 vector.
[[ 4.1]
 [-3.9]
 [ 6.4]]
(3, 1) <class 'numpy.ndarray'> float64

This is a scalar.
5.6
<class 'float'>


<br>
## 2. Matrix addition and scalar-matrix multiplication
<hr>

### 2.1 Matrix addition
Example:
$$
\begin{array}{cccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right] & + & 
\left[ 
\begin{array}{cccc}
2.7 & 7.3\\ 
3.5 & 2.4 \\ 
6.0 & -1.1
\end{array} 
\right]
& = &
\left[ 
\begin{array}{cccc}
4.1+2.7 & 5.3+7.3\\ 
-3.9+3.5 & 8.4+2.4 \\ 
6.4+6.0 & -1.8-1.1
\end{array} 
\right]\\
3 \times 2 &+& 3 \times 2 &=& 3 \times 2
\end{array} 
$$

All matrix and vector operations must satisfy dimensionality properties. For example, it is not allowed to add two matrices of different dimentionalities, such as

$$
\begin{array}{cccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right] & + & 
\left[ 
\begin{array}{cccc}
2.7 & 7.3 & 5.0\\ 
3.5 & 2.4 & 2.8 \\ 
\end{array} 
\right]
& = &
\textrm{Not allowed}\\ 
3 \times 2 &+& 2 \times 3 &=& \textrm{Not allowed}
\end{array} 
$$




### 2.1 Scalar-matrix multiplication
Example:
$$
\begin{array}{cccc}
3 &\times& \left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
3 \times 4.1 & 3 \times 5.3\\ 
3 \times -3.9 & 3 \times 8.4 \\ 
3 \times 6.4 & 3 \times  -1.8
\end{array} 
\right]\\
\textrm{No dim} &+& 3 \times 2 &=& 3 \times 2
\end{array} 
$$


<br>

### Question 2: Add the two matrices, and perform the multiplication scalar-matrix as above in Python

In [17]:
import numpy as np

# define matrices
X1 =  np.array([[ 4.1, 5.3], [-3.9, 8.4], [ 6.4, -1.8]])
X2 =  np.array([[ 2.7, 3.5], [ 7.3, 2.4], [ 5.0, 2.8]])

# matrix addition
X3 = X1+X2

# scalar-matrix muplication
X4 = 3*X3

print(X1,X2,X3,X4,sep='\n')

[[ 4.1  5.3]
 [-3.9  8.4]
 [ 6.4 -1.8]]
[[2.7 3.5]
 [7.3 2.4]
 [5.  2.8]]
[[ 6.8  8.8]
 [ 3.4 10.8]
 [11.4  1. ]]
[[20.4 26.4]
 [10.2 32.4]
 [34.2  3. ]]


<br>
## 3. Matric-vector multiplication
<hr>

### 3.1 Example
Example:
$$
\begin{array}{cccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]  
&\times &
\left[ 
\begin{array}{cccc}
2.7 \\ 
3.5 \\ 
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
4.1\times 2.7 + 5.3\times 3.5\\ 
-3.9\times 2.7 + 8.4\times 3.5 \\ 
6.4\times  2.7  -1.8\times 3.5
\end{array} 
\right]\\
 3 \times 2 && 2 \times 1 &=&  3 \times 1
\end{array} 
$$

Dimension of the matric-vector multiplication operation is given by contraction of $3 \times 2$ with $2 \times 1$ = $3 \times 1$.


### 3.2 Formalization
$$
\begin{array}{cccc}
\huge[ 
A
]  
&\times &
\huge[ 
x
]
&=& 
\huge[ 
y
]
\\
m \times n && n \times 1 &=&  m \times 1
\end{array}
$$

Element $y_i$ is given by multiplying the $i^{th}$ row of $A$ with vector $x$:

$$
\begin{array}{cccc}
y_i&=&A_{i}&&x\\
1 \times 1 &=&  1 \times n  &\times&  n \times 1
\end{array}
$$

It is not allowed to multiply a matrix $A$ and a vector $x$ with different $n$ dimensions such as 

$$
\begin{array}{cccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]  
&\times &
\left[ 
\begin{array}{cccc}
2.7 \\ 
3.5 \\ 
-7.2 \\ 
\end{array} 
\right]
&=&
\quad ?\\
3 \times 2 &\times &  3 \times 1  &=& \textrm{not allowed}
\end{array} 
$$


<br>

### Question 3: Multiply the matrix and vector above in Python 

In [19]:
import numpy as np

# define matrices
A =  np.array([[ 4.1, 5.3], [-3.9, 8.4], [ 6.4,-1.8]])
x = np.array([[ 2.7], [ 3.5]])

# matrix-vector multiplication
y = np.dot(A,x)

print(A,x,y,sep='\n')


[[ 4.1  5.3]
 [-3.9  8.4]
 [ 6.4 -1.8]]
[[2.7]
 [3.5]]
[[29.62]
 [18.87]
 [10.98]]


<br>
## 4. Matrix-matrix multiplication
<hr>

### 4.1 Example

$$
\begin{array}{cccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]  
&\times &
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
4.1\times 2.7 + 5.3\times 3.5 & 4.1\times 3.2 + 5.3\times -8.2\\ 
-3.9\times 2.7 + 8.4\times 3.5 & -3.9\times 3.2 + 8.4\times -8.2 \\ 
6.4\times  2.7  -1.8\times 3.5 & 6.4\times  3.2  -1.8\times -8.2
\end{array} 
\right]\\
3 \times 2 &\times &  2 \times 2 &=&  3 \times 2
\end{array}
$$

Dimension of the matrix-matrix multiplication operation is given by contraction of $3 \times 2$ with $2 \times 2$ = $3 \times 2$.


### 4.2 Formalization
$$
\begin{array}{cccc}
\huge[ 
A
]  
&\times &
\huge[ 
X
]
&=& 
\huge[ 
Y
]
\\
m \times n && n \times p &=&  m \times p
\end{array}
$$

Like for matrix-vector multiplication, matrix-matrix multiplication can be carried out only if $A$ and $X$ have the same $n$ dimension.


### 4.3 Linear algebra operations can be parallelized/distributed
Column $Y_i$ is given by multiplying matrix $A$ with the $i^{th}$ column of $X$:

$$
\begin{array}{cccc}
Y_i&=&A &\times & X_i\\
1 \times 1 &=&  1 \times n  &\times&  n \times 1
\end{array}
$$

Observe that all columns $X_i$ are independent. Consequently, all columns $Y_i$ are also independent. This allows to vectorize/parallelize linear algebra operations on (multi-core) CPUs, GPUs, clouds, and consequently to solve all linear problems (including linear regression) very efficiently, basically with one single line of code ($Y=AX$ for millions/billions of data). With Moore's law (computers speed increases by 100x every decade), it has introduced a computational revolution in data analysis. 


<br>

### Question 4: Multiply the two matrices above in Python

In [21]:
import numpy as np

# define matrices
A = np.array([[ 4.1, 5.3], [-3.9, 8.4], [ 6.4,-1.8]])
X = np.array([[ 2.7,3.2], [ 3.5,-8.2]])

# matrix-matrix multiplication
Y = np.dot(A,X)

print(A,X,Y,sep='\n')


[[ 4.1  5.3]
 [-3.9  8.4]
 [ 6.4 -1.8]]
[[ 2.7  3.2]
 [ 3.5 -8.2]]
[[ 29.62 -30.34]
 [ 18.87 -81.36]
 [ 10.98  35.24]]


<br>
## 5. Some linear algebra properties
<hr>

### 5.1 Matrix multiplication is *not* commutative

$$
\begin{array}{cccc}
A &\times& B &\not=& B &\times& A\\
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]  
&\times &
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&\not=&
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&\times &
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]
\end{array} 
$$
<br>


### 5.2 Scalar multiplication is associative

$$
\begin{array}{cccc}
\alpha &\times& B &=& B &\times& \alpha\\
4.1  &\times&
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&\times&
4.1
\end{array}
$$
<br>


### 5.3 Transpose matrix

$$
\begin{array}{cccc}
X^T_{ij} &=& X_{ji}\\
\left[ 
\begin{array}{cccc}
2.7 & 3.2 & 5.4 \\ 
3.5 & -8.2 & -1.7\\ 
\end{array} 
\right]^T
&=&
\left[ 
\begin{array}{cccc}
2.7 & 3.5\\
3.2 & -8.2 \\ 
5.4 & -1.7\\ 
\end{array} 
\right]
\end{array}
$$
<br>


### 5.4 Identity matrix

$$
I=I_{n}=Diag([1,1,...,1])
$$

such that

$$
I\times A = A \times I
$$

Examples:
$$
I_2=
\left[ 
\begin{array}{cccc}
1 & 0\\
0 & 1  
\end{array} 
\right]
$$

$$
I_3=
\left[ 
\begin{array}{cccc}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1  
\end{array} 
\right]
$$
<br>

### 5.5 Matrix inverse

For any square $n\times n$ matrix $A$, the matrix inverse $A^{-1}$ is defined as

$$
AA^{-1} = A^{-1}A = I
$$

Example:

$$
\begin{array}{cccc}
\left[ 
\begin{array}{cccc}
2.7 & 3.5\\
3.2 & -8.2 
\end{array} 
\right]
&\times &
\left[ 
\begin{array}{cccc}
0.245 & 0.104 \\ 
0.095 & -0.080
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
1 & 0\\
0 & 1  
\end{array} 
\right]\\
A&\times &A^{-1} &=& I
\end{array}
$$


Some matrices do not hold an inverse such as zero matrices. They are called degenerate or singular.
<br>



<br>

### Question 5: Compute the matrix transpose as above in Python. Determine also the matrix inverse in Python.
Hint: You may use numpy attribute *.T* and function *np.linalg.inv()*.

In [25]:
import numpy as np

# define matrices
A = np.array([[2.7,3.2,5.4],[3.5,-8.2,-1.7]])
B = np.array([[2.7,3.5],[3.2,-8.2]])

# transpose operation
A_transpose = A.T

# inverse operation
B_inv = np.linalg.inv(B)

print(A,A_transpose,B,B_inv,sep='\n')


[[ 2.7  3.2  5.4]
 [ 3.5 -8.2 -1.7]]
[[ 2.7  3.5]
 [ 3.2 -8.2]
 [ 5.4 -1.7]]
[[ 2.7  3.5]
 [ 3.2 -8.2]]
[[ 0.24595081  0.104979  ]
 [ 0.0959808  -0.0809838 ]]
